/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

/**
 *
 * @author dasun
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDutyPage
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        btnAddEmployee = new javax.swing.JButton();
        btnAddSalary = new javax.swing.JButton();
        btnIssuingDetails = new javax.swing.JButton();
        btnAddTransportation = new javax.swing.JButton();
        btnEmployeeDetails = new javax.swing.JButton();
        btnIngredientsDetails = new javax.swing.JButton();
        btnAddSales = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProductDetails = new javax.swing.JButton();
        btnSalaryDetails = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        btnTransportationDetails = new javax.swing.JButton();
        btnSalesDetails = new javax.swing.JButton();
        btnManageJobRoles = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnCreateProfile = new javax.swing.JButton();
        btnAddIssuingDetails = new javax.swing.JButton();
        btnAddIngredients = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ISP logo.JPG"))); // NOI18N

        btnAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                AddEmployee addEmployee = new AddEmployee();
                addEmployee.page="Admin";
                addEmployee.setVisible(true);
            }
        });

        btnAddSalary.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddSalary.setText("Add Salary");
        btnAddSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                AddSalary addSalary = new AddSalary();
                addSalary.page="Admin";
                addSalary.setVisible(true);
            }
        });

        btnIssuingDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnIssuingDetails.setText("Issuing Details");
        btnIssuingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssuingDetailsActionPerformed(evt);
            }
        });

        btnAddTransportation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddTransportation.setText("Add Transportation");
        btnAddTransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTransportationActionPerformed(evt);
            }
        });

        btnEmployeeDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEmployeeDetails.setText("Employee Details");
        btnEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                EmpDetails empDetails = new EmpDetails();
                empDetails.page="Admin";
                empDetails.setVisible(true);
            }
        });

        btnIngredientsDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnIngredientsDetails.setText("Ingredients Details");
        btnIngredientsDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientsDetailsActionPerformed(evt);
            }
        });

        btnAddSales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddSales.setText("Add Sales ");
        btnAddSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSalesActionPerformed(evt);
            }
        });

        btnAddProduct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnAddOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddOrder.setText("Add Order");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Ceylanica Bio Produvts (Pvt) Ltd");

        btnProductDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnProductDetails.setText("Product Details");
        btnProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductDetailsActionPerformed(evt);
            }
        });

        btnSalaryDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalaryDetails.setText("Salary Details");
        btnSalaryDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                SalaryDetails salaryDetails = new SalaryDetails();
                salaryDetails.page="Admin";
                salaryDetails.setVisible(true);
            }
        });

        btnOrderDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOrderDetails.setText("Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });

        btnTransportationDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTransportationDetails.setText("Transportation Details");
        btnTransportationDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportationDetailsActionPerformed(evt);
            }
        });

        btnSalesDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalesDetails.setText("Sales Details");
        btnSalesDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesDetailsActionPerformed(evt);
            }
        });

        btnManageJobRoles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManageJobRoles.setText("Manage Job Roles");
        btnManageJobRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                JobRoles  jobRoles = new JobRoles();
                jobRoles.setVisible(true);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                Login login = new Login();
                login.setVisible(true);
            }
        });

        btnCreateProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCreateProfile.setText("Create Profile");
        btnCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                CreateProfile createProfile = new CreateProfile();
                createProfile.page="Admin";
                createProfile.setVisible(true);
            }
        });

        btnAddIssuingDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddIssuingDetails.setText("Add Issuing Details");
        btnAddIssuingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIssuingDetailsActionPerformed(evt);
            }
        });

        btnAddIngredients.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddIngredients.setText("Add Ingredients");
        btnAddIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIngredientsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddIssuingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIngredientsDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddSales, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                        .addComponent(btnSalaryDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnProductDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(btnAddTransportation)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btnIssuingDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnManageJobRoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransportationDetails, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOrderDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalesDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreateProfile)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout)
                            .addComponent(btnCreateProfile)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(logo)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderDetails)
                    .addComponent(btnAddSales)
                    .addComponent(btnAddEmployee))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSalary)
                    .addComponent(btnAddTransportation)
                    .addComponent(btnIssuingDetails))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnEmployeeDetails)
                    .addComponent(btnSalesDetails))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOrder)
                    .addComponent(btnSalaryDetails)
                    .addComponent(btnTransportationDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIssuingDetails)
                    .addComponent(btnProductDetails)
                    .addComponent(btnManageJobRoles))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngredientsDetails)
                    .addComponent(btnAddIngredients))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnAddSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSalaryActionPerformed

    private void btnIssuingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssuingDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIssuingDetailsActionPerformed

    private void btnAddTransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTransportationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTransportationActionPerformed

    private void btnEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeDetailsActionPerformed

    private void btnIngredientsDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientsDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngredientsDetailsActionPerformed

    private void btnAddSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSalesActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void btnProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductDetailsActionPerformed

    private void btnSalaryDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalaryDetailsActionPerformed

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void btnTransportationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportationDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransportationDetailsActionPerformed

    private void btnSalesDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesDetailsActionPerformed

    private void btnManageJobRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageJobRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageJobRolesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateProfileActionPerformed

    private void btnAddIssuingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIssuingDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddIssuingDetailsActionPerformed

    private void btnAddIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIngredientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddIngredientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnAddIngredients;
    private javax.swing.JButton btnAddIssuingDetails;
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddSalary;
    private javax.swing.JButton btnAddSales;
    private javax.swing.JButton btnAddTransportation;
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton btnEmployeeDetails;
    private javax.swing.JButton btnIngredientsDetails;
    private javax.swing.JButton btnIssuingDetails;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageJobRoles;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnProductDetails;
    private javax.swing.JButton btnSalaryDetails;
    private javax.swing.JButton btnSalesDetails;
    private javax.swing.JButton btnTransportationDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
